### ISSUE TITLE
SDL2: Framerate issues on Mac OS X without external monitor

### ISSUE THREAD

**Issue by galexandreg** [pygame/pygame#1032]
I have a strange framerate issue on Mac OS X when using pygame2.
When I run a program on my MacBookPro without any external monitor, the performance is horrible.
This is using a simple 1080p monitor connected to my old MacBookPro with a 1280 x 800 screen.

- If I unplug the external monitor and start the program (using only the MacBook display), I get fluctuating performance with an average of 30fps all the time. 

- If I use the external monitor, it's 60fps, almost as steady as pygame1. So it's much worse without the external monitor plugged in.

Where the pygame window is doesn't matter, only the fact that it is plugged in.

If I start the program when the external monitor is plugged in, the performance will stay good even if I unplug it. It will also stay bad if I start it without the external monitor and plug it back in after.

The same programs with SDL1 are 60fps all the time without any drops, even when I have 100+ sprites moving at the same time.

I also did tests with the new textures and renderers to see if it would help but it doesn't change anything.

- With the MacBookPro monitor only I get the same bad performance that fluctuates between 30 and 100+ fps for small amounts of time

- With the external monitor, I get a steady 60 fps on both versions... but not more, even if I don't limit the fps.

Test using surfaces:
```
import pygame
import sys

pygame.init()
window = pygame.display.set_mode((800, 600))
clock = pygame.time.Clock()

square = pygame.Surface((10, 10))
square.fill((255, 0, 0))

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()

    window.blit(square, (0, 0))
    pygame.display.flip()
    clock.tick()
    print(int(clock.get_fps()))

```

Test using textures and renderers:
```
import pygame
from pygame._sdl2 import Window, Texture, Renderer
import sys

pygame.init()
window = Window('TESTSDL2', size=(800, 600))
renderer = Renderer(window)
clock = pygame.time.Clock()

square = pygame.Surface((10, 10))
square.fill((255, 0, 0))
square_texture = Texture.from_surface(renderer, square)

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
            
    renderer.clear()
    renderer.copy(square_texture, dstrect=(0, 0, 10, 10))
    renderer.present()
    clock.tick()
    print(int(clock.get_fps()))
```

Pygame 2.0.0.dev1, SDL 2.0.9, python 3.7.3, MacOS 10.14.4

**Comment by galexandreg** [comment]
Using the example code from another OS X performance issue that was closed because it if fixed in SDL2: https://github.com/pygame/pygame/issues/440

Here is a sample from the framerate output that clearly shows what I mean:
`46.94835662841797
46.94835662841797
46.94835662841797
46.94835662841797
46.94835662841797
46.94835662841797
46.94835662841797
46.94835662841797
46.94835662841797
46.94835662841797
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
35.335689544677734
30.1204833984375
30.1204833984375
30.1204833984375
30.1204833984375
30.1204833984375
30.1204833984375
30.1204833984375
30.1204833984375
30.1204833984375
30.1204833984375
181.81817626953125
181.81817626953125
181.81817626953125
181.81817626953125
181.81817626953125
181.81817626953125
181.81817626953125
181.81817626953125
181.81817626953125
181.81817626953125
35.971221923828125
35.971221923828125
35.971221923828125
35.971221923828125
35.971221923828125
35.971221923828125
35.971221923828125
35.971221923828125
35.971221923828125
35.971221923828125`

Performance is mostly bad and sometimes goes up or a moment.

If I plug in my external monitor (not even displaying the example on it):
`370.370361328125
370.370361328125
370.370361328125
370.370361328125
370.370361328125
370.370361328125
370.370361328125
370.370361328125
370.370361328125
370.370361328125
79.36508178710938
79.36508178710938
79.36508178710938
79.36508178710938
79.36508178710938
79.36508178710938
79.36508178710938
79.36508178710938
79.36508178710938
79.36508178710938
59.88024139404297
59.88024139404297
59.88024139404297
59.88024139404297
59.88024139404297
59.88024139404297
59.88024139404297
59.88024139404297
59.88024139404297
59.88024139404297
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
59.88024139404297
59.88024139404297
59.88024139404297
59.88024139404297
59.88024139404297
59.88024139404297
59.88024139404297
59.88024139404297
59.88024139404297
59.88024139404297
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.240966796875
60.60606002807617
60.60606002807617
60.60606002807617
60.60606002807617
60.60606002807617
60.60606002807617
`

So not having an external monitor makes pygame2 unusable...

**Comment by galexandreg** [comment]
I did some more testing to try to narrow it down a little.
I used to the SDL2 example code to do a version with the new textures and renderers to see if it changed anything and it doesn't help.

- With the MacBookPro monitor only I get the same bad performance that fluctuates between 30 and 100+ fps for small amounts of time

- With the external monitor, I get a steady 60 fps on both versions... but not more, even if I don't limit the fps. 

SDL1 version:
```
import pygame
import sys

pygame.init()
window = pygame.display.set_mode((800, 600))
clock = pygame.time.Clock()

square = pygame.Surface((10, 10))
square.fill((255, 0, 0))

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()

    window.blit(square, (0, 0))
    pygame.display.flip()
    clock.tick()
    print(int(clock.get_fps()))

```

SDL2 version:
```
import pygame
from pygame._sdl2 import Window, Texture, Renderer
import sys

pygame.init()
window = Window('TESTSDL2', size=(800, 600))
renderer = Renderer(window)
clock = pygame.time.Clock()

square = pygame.Surface((10, 10))
square.fill((255, 0, 0))
square_texture = Texture.from_surface(renderer, square)

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
            
    renderer.clear()
    renderer.copy(square_texture, dstrect=(0, 0, 10, 10))
    renderer.present()
    clock.tick()
    print(int(clock.get_fps()))


```

**Comment by illume** [comment]
Thanks for providing a couple of different test cases.

- Currently pygame 2 with sdl2 does not have vsync enabled by default, but we probably will enable that by default. Using something like `clock.tick(60)` is probably a good idea.
- the performance on Mac will change on SDL 2.0.10 because it is switching to the Metal renderer by default (that is the plan, we will see for sure once the release happens). The SDL 2.0.9 is supposed to have various bugs and improvements which are fixed in the coming release.
- sounds like the external monitor being plugged in may enable vsync. There are some issues with this in SDL2 on the most recent MacOS version.
- perhaps it's something to do with hidpi or the format of the pixels (some pixel formats are more optimized with different graphics cards, and plugging in an external monitor can enable the discrete GPU in the macbooks... see the activity monitor to see if the GPU is being used).
- SDL_HINT_RENDER_DRIVER=metal python rendererexample.py

It might be worth reporting a bug to the SDL people. Especially if you can reproduce the issue with a normal SDL C program to make it easier for them. Or add the clock.tick, and wait for the metal renderer to be released in SDL 2.0.10 (which hopefully fixes these issues).

**Comment by galexandreg** [comment]
Thanks for taking the time to answer.

Adding `clock.tick(60)` does make it more stable, but it still won't go higher than 30fps without the external monitor.

It probably doesn't have anything to do with high dpi or discrete GPU being activated because the MacBook I use doesn't have them. It's an old 13" with only the Intel integrated graphics, but it's still supported by Apple and can run Metal. I guess that people with more powerful hardware may not see the issue if the frame rate drop doesn't make it too slow. Let's hope switching to  Metal by default in the next SDL release will fix the issues.

**Comment by kfu02** [comment]
I have this same issue too: ```clock.tick(60)``` and ```clock.tick(30)``` are both still worse when I have no external monitor plugged in.

**Comment by notpygame** [comment]
Thanks @kfu02 . Can you please confirm which pygame and SDL version you are using?

**Comment by kfu02** [comment]
Pygame 1.9.6, python 3.6.5, SDL2 (2.0.8).

**Comment by galexandreg** [comment]
The problems linked by @kfu02 above are related to Pygame1 with SDL 1. It does seem that the Retina display was causing some problems, bit it isn't the case in this situation as I don't have a high dpi display. The performance on Mac was always worse, but the specific problem here is that it is way worse with SDL2, specifically when I have no external monitor.

@kfu02 Because pygame 1.9.6 still comes with SDL1, I assume you compiled it yourself with SDL2 instead of using Pygame2.0.0.dev1? If that's the case, is the performance better when using SDL1 on the Mac?

**Comment by notpygame** [comment]
@galexandreg are you able to reproduce the issue with this simple C SDL2 program?
https://github.com/illume/pygame4000/blob/master/code/sdl2_basics_tutorial_fundamentals/hey.c

```bash
brew install sdl2
wget https://raw.githubusercontent.com/illume/pygame4000/master/code/sdl2_basics_tutorial_fundamentals/hey.c
gcc -o hey hey.c `sdl2-config --cflags --libs`
./hey
```

If so, then we can make a very nice bug report to the SDL folks :)


You could also try the SDL2 from hg with some commands like this (be careful to understand these commands as it might break programs you are using)
```
brew uninstall --ignore-dependencies sdl2
brew install sdl2 --head
```

**Comment by galexandreg** [comment]
I kind of feel bad about this, but I don't want to simply ignore it and pretend I forgot about it.

The thing is, I am completely new to programming and I only do this as a hobby on my spare time. I never used Brew before and I don't have the Apple development tools installed (gcc isn't installed by default on OS X right?).
As much as I would love to help, I also don't want to test stuff I don't really understand yet. If I get there in my learning process soon enough, I will certainly test it and share the results here.

I also wonder if it would be even worth the effort to fix. If the issue only affects non-retina internal Mac displays (or maybe even my specific monitor/graphics hardware combination), the problem will fix itself  when Apple stops supporting these older models (probably in the next year or two...)

**Comment by illume** [comment]
@galexandreg hey hey. Don't feel bad.

Thanks heaps for reporting this :)

I'll try and reproduce the issue, and send it to the SDL folks.

**Comment by galexandreg** [comment]
When testing issue #1169, I realized that the frame rate problem not only occurs without an external monitor, but also if the only monitor is the external one (by closing the laptop screen, it seems do disable the internal one.)

So the problem isn't related to the resolution of the external screen being more "standard" or some other functionality I don't know about. Strangely enough, the frame rate is good and stable only if I have 2 monitors available. If I have only one, whether it's the internal or the HD one, it doesn't work.

**Comment by galexandreg** [comment]
The issue is fixed in Pygame2.0.0dev4 with SDL 2.0.10. The framerate is now stable at 60FPS, external monitor or not, like it was with the SDL1 versions.

**Comment by illume** [comment]
Wonderful :)

**Comment by galexandreg** [comment]
I had the same problem today and I wonder if something changed again or if I was wrong last time... maybe I forgot to test properly 🤔 I don't know...

Anyway it looks like it's a vsync issue because I dont have the problem when using pygame.SCALED and vsync=True. When I'm not, the performance is horrible unless I have two monitors. Somehow, it seems to enable vsync.

Anyway, I thought it could be useful to add this information here in case others have the same problem in the future.
If the performance on mac seems really bad by default, try using pygame.SCALED and enabling vsync.
