### ISSUE TITLE
Arcs with width values greater than 1 being drawn with tiny holes/gaps

### ISSUE THREAD

**Issue by MightyJosip** [pygame/pygame#1663]
Arcs drawn with width values greater than 1 may contain tiny holes/gaps. This is shown by the following code as the resulting arc contains tiny gaps where it should be a solid color.

    import pygame
    import time

    pygame.display.init()
    screen = pygame.display.set_mode((100, 100))
    rect = pygame.Rect((0, 0), (80, 70))
    rect.center = screen.get_rect().center

    pygame.draw.arc(screen, pygame.Color('yellow'), rect, 1, 2, 35)
    pygame.display.flip()

    time.sleep(10)
    pygame.display.quit()

Resulting arc with tiny gaps.

![image](https://user-images.githubusercontent.com/29337110/80218691-cab3d200-8641-11ea-9f4f-0ede7984b472.png)

System details:

    os: windows 10 (64bit)
    python: 3.7.4 (64bit)
    pygame: 2.0.0.dev7 (SDL: 2.0.12)

**Related docs:** https://www.pygame.org/docs/ref/draw.html#pygame.draw.arc

**Comment by Mushguys** [comment]
This looks to me like the resolution of the arc is too low. I can't be sure without seeing the code.
Where is the code for drawing arcs?

**Comment by MightyJosip** [comment]
Another example

```
import pygame
pygame.display.init()
screen = pygame.display.set_mode((200, 200))
rect = pygame.Rect((0, 0), (180, 170))
rect.center = screen.get_rect().center
pygame.draw.arc(screen, pygame.Color('yellow'), rect, 1, 2, 70)
pygame.display.flip()
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            quit()
```

Source code for drawing arc:
front-end: https://github.com/pygame/pygame/blob/master/src_c/draw.c#L498-L574
algorithm: https://github.com/pygame/pygame/blob/master/src_c/draw.c#L1326-L1371

**Comment by Mushguys** [comment]
The problem seems to be here:
[https://github.com/pygame/pygame/blob/master/src_c/draw.c#L556-L560](https://github.com/pygame/pygame/blob/master/src_c/draw.c#L556-L560)
This code draws multiple arcs to make up a single, wider arc. The radii of the arcs are drawn at one-pixel intervals, which is large enough for holes in between the arcs. A smaller interval should fix it, but I'm not sure just how small.

**Comment by Loupau38** [comment]
Hi, I've installed pygame 2.5.2 which fixes this issue with the above code snippets but I still get it with the following code :
```
import pygame
import time
s = pygame.display.set_mode((700, 700))
pygame.draw.arc(s,(255,255,255),
    pygame.Rect(100,100,500,500),
    0,
    1.5,100)
pygame.display.flip()
time.sleep(10)
pygame.display.quit()
```
![image](https://github.com/pygame/pygame/assets/78562395/4f79d697-3be2-4d20-8658-446ff60fa016)

**Comment by sampottinger** [comment]
Yeah this may need to be reopened :( @illume and @MightyJosip

**Comment by daveprobst** [comment]
should be reopened. I have the same issue @illume

**Comment by ununnamed** [comment]
or use this function that replaces the original code
`import pygame
import math
import time


def draw_thick_arc(surface, color, rect, start_angle, stop_angle, width, segments=100):
    """Draw a thick arc using polygon approximation"""
    width = min(width, rect.height // 2)  # Ensure width doesn't exceed half the height

    # Calculate inner and outer radii
    outer_radius = min(rect.width, rect.height) // 2
    inner_radius = outer_radius - width

    # Calculate center point
    center_x = rect.centerx
    center_y = rect.centery

    # Convert angles from radians (pygame uses radians for draw.arc)
    start_angle_rad = start_angle
    stop_angle_rad = stop_angle

    # Calculate angle step
    angle_step = (stop_angle_rad - start_angle_rad) / segments

    # Generate points for outer and inner arcs
    points = []

    # Outer arc points (clockwise)
    for i in range(segments + 1):
        angle = start_angle_rad + i * angle_step
        x = center_x + outer_radius * math.cos(angle)
        y = center_y + outer_radius * math.sin(angle)
        points.append((x, y))

    # Inner arc points (counter-clockwise)
    for i in range(segments + 1):
        angle = stop_angle_rad - i * angle_step
        x = center_x + inner_radius * math.cos(angle)
        y = center_y + inner_radius * math.sin(angle)
        points.append((x, y))

    # Draw the polygon
    if len(points) > 2:
        pygame.draw.polygon(surface, color, points)


# Example usage
pygame.init()
screen = pygame.display.set_mode((400, 400))
rect = pygame.Rect((0, 0), (300, 300))
rect.center = screen.get_rect().center

screen.fill((0, 0, 0))
start_time = time.perf_counter()
draw_thick_arc(screen, pygame.Color('yellow'), rect, 1, 2, 35)
pygame.display.flip()
draw_time = (time.perf_counter() - start_time) * 1000  # Convert to milliseconds
print(draw_time)

time.sleep(5)
pygame.quit()`
