### ISSUE TITLE
Window does not get focus on OS X with Python 3

### ISSUE THREAD

**Issue by illume** [pygame/pygame#203]
Originally reported by: **Ian McCowan (Bitbucket: [valrus](https://bitbucket.org/valrus), GitHub: [valrus](https://github.com/valrus))**

----------------------------------------

A pygame window created using the code below on OS X using the latest pygame source:
```
#!python

import pygame

pygame.init()
screen = pygame.display.set_mode((640, 480))

done = False
while not done:
    pygame.event.pump()
    keys = pygame.key.get_pressed()
    if keys[pygame.K_ESCAPE]:
        done = True
    if keys[pygame.K_SPACE]:
        print("got here")
    events = pygame.event.get()
    for event in events:
        if event.type == pygame.MOUSEBUTTONDOWN:
            print("mouse at ", event.pos)
```
does not receive any keyboard input. It is not possible to trigger the "got here" message nor cause it to terminate using Escape; instead all keypresses show up in the terminal window from which the script was run. This happens even though the window appears to have focus.

Additionally, based on the mouse event handling, the window exhibits some combination of the incorrect mouse behavior described in these two issues:
#79/pygame-incompatible-with-osx-lion-trackpad
#163/no-mouse-move-events-unless-mouse-button
viz. all subsequent clicks register with the same position as the first one, and the only way to update its position is to click and drag to a new location.

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/203

**Comment by takluyver** [comment]
@glyph has made a workaround for this kind of issue called [venvdotapp](https://github.com/glyph/venvdotapp) - the idea is that you run it in a virtualenv to put Python in the necessary format so that things work.

```
pip install venvdotapp
venvdotapp
```

I haven't tried it myself (I don't have a Mac, so I wouldn't).

**Comment by ironsmile** [comment]
I've tried `venvdotapp` and it does the trick! The PyGame window can now be focused and keyboard works. I am using the following:

* OSX 10.11.6
* Python 3.5.2 in venv
* PyGame 1.9.2 built locally

**Comment by jyhong836** [comment]
I also try @takluyver 's solution. It clearly works. Thank you so much!

+ macOS 10.13.3
+ Python (3.6.4) in virtualenv
+ pip (9.0.1)
+ pygame (1.9.4.dev0)  which is installed using `pip install hg+http://bitbucket.org/pygame/pygame`

**Comment by cafpereira** [comment]
@jyhong836 
I am having the same issue. Trying to use pygame in the example project of my Python Crash Course book (https://ehmatthes.github.io/pcc/chapter_12/README.html)

I installed venvdotapp sucessfully, and it seems this tool packages the current virtual env project as a OSX `app` file right?

Then, when I double click the generated app file I got this error message: 
"You can't open the application XYZ because PowerPC applications are no longer supported."

Is there anything I am missing there?

My system conf:
macOS 10.11.6
Python (3.6.4) in virtualenv
pip (9.0.1)

**Comment by jyhong836** [comment]
@cafpereira 
> I installed venvdotapp sucessfully, and it seems this tool packages the current virtual env project as a OSX app file right?

Yes, it does package the virtual environment. 

> Then, when I double click the generated app file I got this error message:
> "You can't open the application XYZ because PowerPC applications are no longer supported."

I didn't click the generated app file, and I don't think it is necessary. I assume your virtual environment is 'XYZ'.

Below is what I did.
```bash
$ pip install venvdotapp
(XYZ) $ venvdotapp # inside my venv named 'XYZ'
plistloc /Users/my_username/.virtualenvs/XYZ/bin/XYZ.app/Contents/Info.plist
apppy /Users/my_username/.virtualenvs/XYZ/bin/XYZ.app/Contents/MacOS/python
realpython /Users/my_username/.virtualenvs/XYZ/bin/python3.6
```
You can find the last two lines of ouputs say there is an app, `/Users/my_username/.virtualenvs/XYZ/bin/XYZ.app` and a python is inside it, which points to `/Users/my_username/.virtualenvs/XYZ/bin/python3.6` indeed.
Then you can run 
```
(XYZ) $ python some_pygame_script.py
```
which works for me.

I think the mechanism is that the `venvdotapp` makes the system think the `python` is some framework software. But actually, it is a link.

**Comment by cafpereira** [comment]
@jyhong836 Oh I see what you saying now. You right, its working like charm, thanks a lot!

**Comment by illume** [comment]
-Hrmm. I tried to use venvdotapp with no luck (log, and errors below), I did have luck without it.
- Mac OSX 10.11.6, python36, homebrew (with sdl stuff installed).

venvdotapp failing...
```
15:53:04-rene~$ python3 -m venv /tmp/anenv36
15:53:33-rene~$ . /tmp/anenv36/bin/activate
(anenv36) 15:53:42-rene~$ pip install venvdotapp
Collecting venvdotapp
  Downloading venvdotapp-0.0.2-py2.py3-none-any.whl
Installing collected packages: venvdotapp
Successfully installed venvdotapp-0.0.2
(anenv36) 15:53:49-rene~$ venvdotapp
plistloc /private/tmp/anenv36/bin/anenv36.app/Contents/Info.plist
apppy /private/tmp/anenv36/bin/anenv36.app/Contents/MacOS/python
realpython /usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/bin/python3.6
(anenv36) 15:53:53-rene~$ pip install pygame oo
Collecting pygame
  Using cached pygame-1.9.3-cp36-cp36m-macosx_10_9_intel.whl
Collecting oo
  Using cached oo-1.1.tar.gz
Installing collected packages: pygame, oo
  Running setup.py install for oo ... done
Successfully installed oo-1.1 pygame-1.9.3
(anenv36) 15:54:04-rene~$ python -moo
/usr/local/opt/python3/bin/python3.6: No module named oo
(anenv36) 15:54:55-rene~$ python
Python 3.6.0 (default, Dec 24 2016, 00:01:50) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pygame'
>>> 
(anenv36) 15:55:03-rene~$ /tmp/anenv36/bin/python
Python 3.6.0 (default, Dec 24 2016, 00:01:50) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pygame'
>>> 
```

Working with this:
```
15:58:34-rene~$ python3 -m venv /tmp/anenv362
15:58:40-rene~$ . /tmp/anenv362/bin/activate
(anenv362) 15:58:52-rene~$ pip install pygame oo
Collecting pygame
  Using cached pygame-1.9.3-cp36-cp36m-macosx_10_9_intel.whl
Collecting oo
  Using cached oo-1.1.tar.gz
Installing collected packages: pygame, oo
  Running setup.py install for oo ... done
Successfully installed oo-1.1 pygame-1.9.3
(anenv362) 15:58:59-rene~$ python -moo
2018-02-14 15:59:02.507 Python[45607:7315654] 15:59:02.507 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
(anenv362) 15:59:04-rene~$ python -m pygame.examples.aliens
2018-02-14 15:59:13.608 Python[45613:7315762] 15:59:13.608 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
```

**Comment by illume** [comment]
Ok, I got it working.  I guess venvdotapp doesn't update the `pip` executable. When I install with `python -m pip` it works.

```
16:20:52-rene~$ python3 -m venv /tmp/anenv36
anenv36/  anenv362/ 
16:20:52-rene~$ python3 -m venv /tmp/anenv363
16:21:06-rene~$ . /tmp/anenv363/bin/activate
(anenv363) 16:21:25-rene~$ python -m pip install pygame oo
Collecting pygame
  Using cached pygame-1.9.3-cp36-cp36m-macosx_10_9_intel.whl
Collecting oo
  Using cached oo-1.1.tar.gz
Installing collected packages: pygame, oo
  Running setup.py install for oo ... done
Successfully installed oo-1.1 pygame-1.9.3
(anenv363) 16:21:38-rene~$ python -moo
2018-02-14 16:21:43.709 Python[46285:7328890] 16:21:43.709 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
(anenv363) 16:21:45-rene~$ python -m pygame.examples.aliens
```

**Comment by illume** [comment]
Here are some instructions that I've put on the [GettingStarted](https://www.pygame.org/wiki/GettingStarted) page.

```
python3 -m venv anenv
. ./anenv/bin/activate
python -m pip install venvdotapp
venvdotapp
python -m pip install pygame

# See if pygame works with the oo module, and the aliens example.
python -m pip install oo
python -moo
python -m pygame.examples.aliens
```

**Comment by illume** [comment]
@jyhong836 Thank you! I had a little brain fart there it seems. I updated the GettingStarted wiki page https://www.pygame.org/wiki/GettingStarted#Mac%20installation

**Comment by illume** [comment]
Also added instructions about using pythonw for Anaconda to https://www.pygame.org/wiki/GettingStarted#Mac%20installation

**Comment by illume** [comment]
The two mac related files in pygame for handling this type of thing are:
- https://github.com/pygame/pygame/blob/master/lib/macosx.py
- https://github.com/pygame/pygame/blob/master/src/sdlmain_osx.m

Perhaps some of what https://github.com/glyph/venvdotapp does could be done in there.

**Comment by ExarKunFan** [comment]
That workaround doesn't works everytime, venvdotapp works if i code something myself and import it in code, but it don't work if i want to try examples. Can we expect fix in soon future releases? Or we should wait for 2.0?

**Comment by takluyver** [comment]
AFAIK, we don't know how to fix it. Glyph understands it better than any of us appear to, and venvdotapp is his fix. @illume found that it seemed to work with SDL 2, so if that's consistent, pygame 2.0 ought to resolve it.

**Comment by illume** [comment]
I committed a fix in #415. It seems to fix the icon issue 
If you [Compile from source](https://www.pygame.org/wiki/MacCompile#Installing%20from%20source%20with%20homebrew) you can try it out.
```
pip install https://github.com/pygame/pygame/archive/master.zip
```

Otherwise, it should be in [pygame 1.9.4](https://github.com/pygame/pygame/issues/390).

**Comment by takluyver** [comment]
Thanks @illume , I underestimated how much you knew about this. :-)

**Comment by illume** [comment]
I think you estimated it about right ;)

**Comment by ExarKunFan** [comment]
Thanks a lot for work, @illume! But i think i should wait for 1.9.4, because after i installed it from source as you mentioned, it says that i am on 1.9.4.dev0. But my pygame window still can't get focus.

**Comment by illume** [comment]
@ExarKunFan sorry, I just merged the PR with the fix in. Would you mind trying it again?

**Comment by ExarKunFan** [comment]
@illume Nice! Now it works like a charm! Thanks a lot!

**Comment by illume** [comment]
Thanks a lot @ExarKunFan for writing back.

**Comment by glyph** [comment]
Sorry for the long delay; venvdotapp had a few bugs in it and I did a new release a little while ago which should have fixed many of them. Please go ahead and report bugs on it if you find more!

**Comment by ReblochonMasque** [comment]
For some reasons, the command `pip install -U https://github.com/pygame/pygame/archive/master.zip` does not compile and leads to a roll back of previous version of pygame.

OSX Sierra 10.12.5

```
    (...)
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of pygame 
```

**Comment by billtubbs** [comment]
I also have this problem.  Installed pygame in an existing Anaconda virtual environment with Python 3.4 on Mac OS X 10.13.3:
```
$ source activate py34
$ pip install -U pygame --user
```
(Cannot focus on pygame window.  Keyboard input goes to terminal.)

But using `pythonw my_game.py` works (thanks @illume).

**Comment by spadix0** [comment]
I also just struggled with this problem: mouse clicks going to pygame, but keypresses and mouse motion going to the window behind:

- OSX 10.12.6
- Python 3.6.5
- pygame 1.9.3
(I'm not sure what is pythonw, but the one available here is 2.7.10, which isn't going to work for me)

Based on my research, the way to solve this problem since 10.6 is to [change the app `activationPolicy` to `Regular`](https://developer.apple.com/documentation/appkit/nsapplicationactivationpolicy?language=objc).

```objc
[NSApp setActivationPolicy: NSApplicationActivationPolicyRegular]
```

As explained in that doc the default policy for unbundled apps is `Prohibited` (which "may not create windows"?)

To test this (and as a workaround, if anyone is interested) I just poked it w/ctypes:

<details>
<summary>Set `NSApp.activationPolicy = Regular` from python</summary>

```python
    from ctypes import cdll, c_int, c_void_p, c_char_p
    from ctypes.util import find_library
    objc = cdll.LoadLibrary(find_library("objc"))
    AppKit = cdll.LoadLibrary(find_library("AppKit"))
    assert objc
    assert AppKit

    getClass = objc.objc_getRequiredClass
    getClass.restype = c_void_p
    getClass.argtypes = (c_char_p,)

    registerName = objc.sel_registerName
    registerName.restype = c_void_p
    registerName.argtypes = (c_char_p,)

    msgSend = objc.objc_msgSend
    msgSend.restype = c_void_p
    msgSend.argtypes = (c_void_p, c_void_p)

    NSAutoreleasePool = getClass(b"NSAutoreleasePool")
    pool = msgSend(NSAutoreleasePool, registerName(b"alloc"))
    pool = msgSend(pool, registerName(b"init"))
    assert pool

    NSApplication = getClass(b"NSApplication")
    app = msgSend(NSApplication, registerName(b"sharedApplication"))
    assert app

    msgSend.restype = c_int
    msgSend.argtypes = (c_void_p, c_void_p, c_int)
    # request regular activation
    rc = msgSend(app, registerName(b"setActivationPolicy:"), 0)
    assert rc

    msgSend.argtypes = (c_void_p, c_void_p)
    msgSend(pool, registerName(b"release"))
```

</details>

...which shows the app in the dock, puts the window in the foreground when it opens and fixes the input problems.

**Comment by illume** [comment]
Hellos,

Note: this issue is closed, and has been fixed in git. You can either install via source, or wait for the 1.9.4 release. https://www.pygame.org/wiki/MacCompile#Installing%20from%20source%20with%20homebrew

**Comment by illume** [comment]
@ReblochonMasque Seems the full stack trace isn't there, so I can't see what the error was for you unfortunately.

**Comment by Waldleufer** [comment]
FYI: 

Error: sdl not installed
Error: sdl_image not installed
Error: sdl_mixer not installed
Error: sdl_ttf not installed
Error: portmidi not installed

These need to be installed to be able to do

`pip install -U https://github.com/pygame/pygame/archive/master.zip`

For some reason pip was not able to execute the command before I installed these.

**Comment by parmentelat** [comment]
Hey there

I'm still running into this bug under the following environment

macos 10.14.4
python 3.7.4  running under conda-4.7.5
pygame==1.9.6

my understanding was that the issue had been fixed with 1.9.4 (which I tried out as well, to no avail) so I am confused.

From the context above I gathered that the issue could be linked to "framework vs non-framework" builds.
Although I am not sure what this means, I intended to run my game through more native python build, but I unfortunately don't have any installed at this point; I can carry out that test if it helps troubleshoot the issue
