### ISSUE TITLE
Pygame on Mac OS X (portmidi crash)

### ISSUE THREAD

**Issue by ak-cuervo** [pygame/pygame#2205]
2019 MacBook Pro

You can get some of this info from the text that pops up in the console when you run a pygame program.

Operating system: macOS Catalina version 10.15.7
Python version: 3.7.9, 3.8.5, 3.9.0
SDL version** (e.g. SDL 2.0.12):
PyGame version: 2.0.0.0.dev10, 2.0.0.0.dev12, 2.0.0.0.dev14

Current behavior: Simple demo app using pygame.midi crashes on the line "import pygame" that indicated that pygame.midi.init() threw a ModuleNotFoundError error from line 79 "import pygame.pypm".

Code:
# https://www.pygame.org/docs/ref/midi.html
import pygame
import pygame.midi
import time

## initialize midi player
pygame.midi.init()
player = pygame.midi.Output(0)
# for the list of MIDI instruments:
#    https://soundprogramming.net/file-formats/general-midi-instrument-list/
player.set_instrument(0)

## play notes
note = (60,0.5,127) # use a tuple to specify (note_tone, duration, velocity)
player.note_on(note[0], note[2])
time.sleep(note[1])
player.note_off(note[0], note[2])

player.note_on(note[0], note[2])
time.sleep(note[1])
player.note_off(note[0], note[2])

note = (67,0.5,127)
player.note_on(note[0], note[2])
time.sleep(note[1])
player.note_off(note[0], note[2])

player.note_on(note[0], note[2])
time.sleep(note[1])
player.note_off(note[0], note[2])

## clean up player and pygame objects
del player
pygame.midi.quit()

**Comment by MyreMylar** [comment]
This should be fixed by this recent pull request in the next version of pygame:

https://github.com/pygame/pygame/pull/2187

**Comment by illume** [comment]
The fix will be included in a dev release later today.

**Comment by ak-cuervo** [comment]
I installed pygame version 2.0.0.0.dev18 but now I it crashes on the line "player=pygame.midi.Output(0)" device out of range.

**Comment by illume** [comment]
Hopefully `pygame==2.0.0.dev20` fixes this properly.

**Comment by ak-cuervo** [comment]
Installed pygame 2.0.0.0.dev20, ran demo program and am still getting device not valid on "player = pygame.midi.Output(0). See attachments.
[pygame installation error 3 (P Liddell 2020.10.16).txt](https://github.com/pygame/pygame/files/5430835/pygame.installation.error.3.P.Liddell.2020.10.16.txt)
[MidiMusicExperiment.txt](https://github.com/pygame/pygame/files/5430840/MidiMusicExperiment.txt)

**Comment by illume** [comment]
Hi,

what does this print?
```
python3 -m pygame.examples.midi --list
```

**Comment by ak-cuervo** [comment]
It essentially returned to the prompt. I copied the following from the terminal session…

(base) pjs-MacBook-Pro-5:~ pj$ python3 -m pygame.examples.midi --list
pygame 2.0.0.dev16 (SDL 2.0.12, python 3.7.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
(base) pjs-MacBook-Pro-5:~ pj$

**Comment by illume** [comment]
Ok, it doesn't look like there are any midi devices. 

MacOS doesn't come with one by default... but fluidsynth is pretty good and easy to install/use.
```bash
$ brew install fluid-synth
```

In one terminal tab start the synth:
```bash
$ fluidsynth -o midi.driver=coremidi -o audio.driver=coreaudio -o audio.coreaudio.device=default -o audio.period-size=256 /usr/local/Cellar/fluid-synth/2.1.2/share/fluid-synth/sf2/VintageDreamsWaves-v2.sf2
```

Then in another terminal you should be able to see the FluidSynth midi device.
```bash
$ python3 -m pygame.examples.midi --list
 4: interface :CoreMIDI:, name :FluidSynth virtual port (21668):, opened :0:  (output)
$ python3 -m pygame.examples.midi --output 4
```
